
logging:
  file: logs/platform-midware-server.log
  level:
    root: INFO
    com:
      cluster: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core: WARN

spring:
  main:
    allow-bean-definition-overriding: true # 存在repo相同的情况 原phis的存储过程与aigw重名
  profiles:
    active:
    - dev
